const API='https://oamhtqvrnhwdrrwzllip.supabase.co';
const KEY='sb_publishable_e35Ve9A05TCQpiE4eo57GA_eehRTOny';
const fallbackProducts=[
 {id:'p1',name:'Rideaux 3 pièces',price:290000,stock:8,category:'Maison',image:'rideaux.png',description:'Coton, longueur 260 cm, plusieurs couleurs.'},
 {id:'p2',name:'Rangement chaussures',price:350000,stock:5,category:'Maison',image:'rangement.webp',description:'Rangement pratique avec 5 étagères.'},
 {id:'p3',name:'Table à manger 4 places',price:2450000,stock:3,category:'Maison',image:'table.png',description:'Design moderne et solide pour votre intérieur.'}
];
let products=[],cart=JSON.parse(localStorage.getItem('ailak_cart')||'[]'),active='Tous';
let session=JSON.parse(localStorage.getItem('ailak_session')||'null'),currentUser=null,currentRole='seller',currentShop=null,myProducts=[];
const $=s=>document.querySelector(s),fmt=n=>new Intl.NumberFormat('fr-FR').format(n)+' GNF';
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
async function request(path,{method='GET',body,headers={}}={}){const h={apikey:KEY,...headers};if(session?.access_token)h.Authorization=`Bearer ${session.access_token}`;if(body!==undefined&&!headers['Content-Type'])h['Content-Type']='application/json';const res=await fetch(API+path,{method,headers:h,body:body===undefined?undefined:(headers['Content-Type']?body:JSON.stringify(body))});if(!res.ok){let msg='Une erreur est survenue';try{const e=await res.json();msg=e.message||e.error_description||e.error||msg}catch{msg=await res.text()||msg}throw new Error(msg)}if(res.status===204)return null;const text=await res.text();return text?JSON.parse(text):null}
async function loadCatalog(){try{const rows=await request('/rest/v1/products?select=id,name,sale_price,stock,category,description,image_url,shop_id&is_published=eq.true&order=created_at.desc');products=rows.map(p=>({...p,price:+p.sale_price,image:p.image_url}))}catch(e){console.warn(e);products=fallbackProducts;toast('Catalogue hors ligne : affichage de secours')}renderCats();renderProducts()}
function renderCats(){const cats=['Tous',...new Set(products.map(p=>p.category))];$('#categories').innerHTML=cats.map(c=>`<button class="chip ${c===active?'active':''}" data-cat="${c}">${c}</button>`).join('');document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{active=b.dataset.cat;renderCats();renderProducts()})}
function renderProducts(){const q=$('#search').value.toLowerCase(),ps=products.filter(p=>(active==='Tous'||p.category===active)&&p.name.toLowerCase().includes(q));$('#products').innerHTML=ps.length?ps.map(p=>`<article class="product"><div class="product-img" ${p.image?`style="background-image:url('${p.image}')"`:''}>${p.image?'':'📦'}</div><div class="product-body"><small>${p.category} · Stock ${p.stock}</small><h3>${p.name}</h3><p>${p.description||'Produit disponible sur Ailak Marketplace.'}</p><div class="product-foot"><strong>${fmt(p.price)}</strong><button class="add" data-add="${p.id}" aria-label="Ajouter au panier">+</button></div></div></article>`).join(''):'<p>Aucun produit publié pour le moment.</p>';document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addCart(b.dataset.add))}
function addCart(id){const p=products.find(x=>x.id===id),x=cart.find(x=>x.id===id);x?x.qty++:cart.push({id:p.id,name:p.name,price:p.price,qty:1});saveCart();toast('Produit ajouté au panier')}
function saveCart(){localStorage.setItem('ailak_cart',JSON.stringify(cart));$('#cartCount').textContent=cart.reduce((s,x)=>s+x.qty,0)}
function renderCart(){$('#cartItems').innerHTML=cart.length?cart.map(x=>`<div class="cart-row"><div><strong>${x.name}</strong><br><small>${x.qty} × ${fmt(x.price)}</small></div><button data-remove="${x.id}">Retirer</button></div>`).join(''):'<p>Votre panier est vide.</p>';$('#cartTotal').textContent=fmt(cart.reduce((s,x)=>s+x.price*x.qty,0));document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{cart=cart.filter(x=>x.id!==b.dataset.remove);saveCart();renderCart()})}
function order(){if(!cart.length)return toast('Ajoutez un produit avant de commander');const name=$('#customerName').value.trim(),phone=$('#customerPhone').value.trim(),area=$('#customerArea').value.trim();if(!name||!phone||!area)return toast('Remplissez votre nom, téléphone et quartier');const lines=cart.map(x=>`• ${x.name} x${x.qty} = ${fmt(x.price*x.qty)}`).join('\n'),total=fmt(cart.reduce((s,x)=>s+x.price*x.qty,0));const message=`Bonjour Ailakshop, je souhaite commander :\n\n${lines}\n\nTotal : ${total}\n\nNom : ${name}\nTéléphone : ${phone}\nLivraison : ${area}\nPaiement : à la livraison`;window.open(`https://wa.me/224622261904?text=${encodeURIComponent(message)}`,'_blank')}
async function login(email,password){const data=await request('/auth/v1/token?grant_type=password',{method:'POST',body:{email,password}});session=data;currentUser=data.user;localStorage.setItem('ailak_session',JSON.stringify(data));await showPrivate()}
async function restoreSession(){if(!session?.access_token)return;try{currentUser=await request('/auth/v1/user');await showPrivate()}catch{localStorage.removeItem('ailak_session');session=null}}
async function logout(){try{await request('/auth/v1/logout',{method:'POST'})}catch{}session=null;currentUser=null;currentShop=null;localStorage.removeItem('ailak_session');$('#privatePanel').hidden=true;$('#loginForm').hidden=false;$('#loginForm').reset();$('#toggleManager').textContent='Se connecter';toast('Déconnexion réussie')}
async function showPrivate(){$('#loginForm').hidden=true;$('#privatePanel').hidden=false;$('#managerPanel').hidden=false;$('#toggleManager').textContent='Masquer l’espace privé';$('#privateEmail').textContent=currentUser.email;const roles=await request(`/rest/v1/user_roles?select=role&user_id=eq.${currentUser.id}`);currentRole=roles[0]?.role||'seller';$('#privateTitle').textContent=currentRole==='admin'?'Administration Ailakshop':'Espace vendeur';const shops=await request(`/rest/v1/shops?select=*&owner_id=eq.${currentUser.id}&limit=1`);currentShop=shops[0]||null;$('#shopSetup').hidden=!!currentShop;$('#productManager').hidden=!currentShop;if(currentShop)await loadMyProducts();$('#adminPanel').hidden=currentRole!=='admin';if(currentRole==='admin')await loadApprovals()}
async function loadMyProducts(){const approvals=await request(`/rest/v1/shop_approvals?select=status&shop_id=eq.${currentShop.id}`),status=approvals[0]?.status||'pending';$('#shopStatus').innerHTML=`Boutique : <strong>${currentShop.name}</strong> · <span class="status-badge status-${status}">${status==='approved'?'Approuvée':status==='rejected'?'Refusée':'En attente de validation'}</span>`;myProducts=await request(`/rest/v1/products?select=*&shop_id=eq.${currentShop.id}&order=created_at.desc`);renderManage()}
function renderManage(){$('#manageList').innerHTML=myProducts.length?myProducts.map(p=>`<div class="manage-item"><div>${p.image_url?`<img class="manage-thumb" src="${p.image_url}" alt="">`:''}<strong>${p.name}</strong><br><small>${fmt(p.sale_price)} · Stock ${p.stock}</small></div><div><button class="secondary" data-edit="${p.id}">Modifier</button><button class="secondary danger" data-del="${p.id}">Supprimer</button></div></div>`).join(''):'<p>Aucun produit ajouté.</p>';document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editProduct(b.dataset.edit));document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>deleteProduct(b.dataset.del))}
function editProduct(id){const p=myProducts.find(x=>x.id===id),f=$('#productForm');f.elements.id.value=p.id;f.elements.name.value=p.name;f.elements.price.value=p.sale_price;f.elements.stock.value=p.stock;f.elements.category.value=p.category;f.elements.description.value=p.description||'';f.scrollIntoView({behavior:'smooth'})}
async function uploadImage(file){const safe=file.name.toLowerCase().replace(/[^a-z0-9._-]/g,'-'),path=`${currentUser.id}/${Date.now()}-${safe}`;await request(`/storage/v1/object/product-images/${path}`,{method:'POST',body:file,headers:{'Content-Type':file.type,'x-upsert':'false'}});return `${API}/storage/v1/object/public/product-images/${path}`}
async function saveProduct(form){const d=Object.fromEntries(new FormData(form)),old=myProducts.find(x=>x.id===d.id);let image_url=old?.image_url||null,file=form.elements.image.files[0];if(file)image_url=await uploadImage(file);const payload={shop_id:currentShop.id,name:d.name,sale_price:+d.price,stock:+d.stock,category:d.category,description:d.description,image_url,is_published:true};if(d.id)await request(`/rest/v1/products?id=eq.${d.id}`,{method:'PATCH',body:payload,headers:{Prefer:'return=minimal'}});else await request('/rest/v1/products',{method:'POST',body:payload,headers:{Prefer:'return=minimal'}});form.reset();await loadMyProducts();await loadCatalog();toast('Produit enregistré')}
async function deleteProduct(id){if(!confirm('Supprimer ce produit ?'))return;await request(`/rest/v1/products?id=eq.${id}`,{method:'DELETE',headers:{Prefer:'return=minimal'}});await loadMyProducts();await loadCatalog();toast('Produit supprimé')}
async function loadApprovals(){const [shops,approvals]=await Promise.all([request('/rest/v1/shops?select=id,name,phone,city,owner_id&order=created_at.desc'),request('/rest/v1/shop_approvals?select=shop_id,status')]),statusMap=Object.fromEntries(approvals.map(a=>[a.shop_id,a.status]));$('#approvalList').innerHTML=shops.map(s=>{const status=statusMap[s.id]||'pending';return `<div class="manage-item"><div><strong>${s.name}</strong><br><small>${s.phone||''} · ${s.city||''}</small><br><span class="status-badge status-${status}">${status}</span></div><div><button class="secondary" data-approve="${s.id}">Approuver</button><button class="secondary danger" data-reject="${s.id}">Refuser</button></div></div>`}).join('')||'<p>Aucune boutique.</p>';document.querySelectorAll('[data-approve]').forEach(b=>b.onclick=()=>setApproval(b.dataset.approve,'approved'));document.querySelectorAll('[data-reject]').forEach(b=>b.onclick=()=>setApproval(b.dataset.reject,'rejected'))}
async function setApproval(shop_id,status){await request(`/rest/v1/shop_approvals?shop_id=eq.${shop_id}`,{method:'PATCH',body:{status,reviewed_by:currentUser.id,reviewed_at:new Date().toISOString()},headers:{Prefer:'return=minimal'}});await loadApprovals();await loadCatalog();toast(status==='approved'?'Boutique approuvée':'Boutique refusée')}
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginMsg').textContent='Connexion…';const d=Object.fromEntries(new FormData(e.currentTarget));try{await login(d.email,d.password);$('#loginMsg').textContent=''}catch(err){$('#loginMsg').textContent=err.message}};
$('#shopForm').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));try{await request('/rest/v1/shops',{method:'POST',body:{owner_id:currentUser.id,name:d.name,phone:d.phone,city:d.city||'Conakry',currency:'GNF',description:d.description},headers:{Prefer:'return=minimal'}});await showPrivate();toast('Boutique créée, en attente de validation')}catch(err){toast(err.message)}};
$('#productForm').onsubmit=async e=>{e.preventDefault();try{await saveProduct(e.currentTarget)}catch(err){toast(err.message)}};
$('#sellerForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));const message=`Bonjour Ailakshop, je souhaite devenir vendeur.\n\nNom : ${d.name}\nTéléphone : ${d.phone}\nBoutique : ${d.shop}`;window.open(`https://wa.me/224622261904?text=${encodeURIComponent(message)}`,'_blank');$('#sellerMsg').textContent='Votre demande est prête dans WhatsApp.'};
$('#search').oninput=renderProducts;$('#cartBtn').onclick=()=>{renderCart();$('#cartDialog').showModal()};$('#closeCart').onclick=()=>$('#cartDialog').close();$('#orderBtn').onclick=order;$('#logoutBtn').onclick=logout;$('#toggleManager').onclick=()=>{const p=$('#managerPanel');p.hidden=!p.hidden;$('#toggleManager').textContent=p.hidden?'Se connecter':session?'Masquer l’espace privé':'Masquer la connexion'};$('#menuBtn').onclick=()=>$('#nav').classList.toggle('open');document.querySelectorAll('#nav a').forEach(a=>a.onclick=()=>$('#nav').classList.remove('open'));
loadCatalog();saveCart();restoreSession();
