const baseProducts=[
 {id:'p1',name:'Rideaux 3 pièces',price:290000,stock:8,category:'Maison',image:'rideaux.png',description:'Coton, longueur 260 cm, plusieurs couleurs.'},
 {id:'p2',name:'Rangement chaussures',price:350000,stock:5,category:'Maison',image:'rangement.webp',description:'Rangement pratique avec 5 étagères.'},
 {id:'p3',name:'Table à manger 4 places',price:2450000,stock:3,category:'Maison',image:'table.png',description:'Design moderne et solide pour votre intérieur.'},
 {id:'p4',name:'Papier peint décoratif',price:230000,stock:12,category:'Décoration',emoji:'🎨',description:'Transformez facilement vos murs.'},
 {id:'p5',name:'Veilleuse moderne',price:200000,stock:7,category:'Décoration',emoji:'💡',description:'Lumière douce pour chambre et salon.'},
 {id:'p6',name:'Téléviseur Smart TV',price:4200000,stock:2,category:'Électronique',emoji:'📺',description:'Image nette et applications connectées.'}
];
let custom=JSON.parse(localStorage.getItem('ailak_products')||'[]'),cart=JSON.parse(localStorage.getItem('ailak_cart')||'[]'),active='Tous';
const $=s=>document.querySelector(s),fmt=n=>new Intl.NumberFormat('fr-FR').format(n)+' GNF',all=()=>[...baseProducts,...custom];
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2400)}
function renderCats(){const cats=['Tous',...new Set(all().map(p=>p.category))];$('#categories').innerHTML=cats.map(c=>`<button class="chip ${c===active?'active':''}" data-cat="${c}">${c}</button>`).join('');document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{active=b.dataset.cat;renderCats();renderProducts()})}
function renderProducts(){const q=$('#search').value.toLowerCase();const ps=all().filter(p=>(active==='Tous'||p.category===active)&&p.name.toLowerCase().includes(q));$('#products').innerHTML=ps.length?ps.map(p=>`<article class="product"><div class="product-img" ${p.image?`style="background-image:url('${p.image}')"`:''}>${p.image?'':p.emoji||'📦'}</div><div class="product-body"><small>${p.category} · Stock ${p.stock}</small><h3>${p.name}</h3><p>${p.description||'Produit disponible sur Ailak Marketplace.'}</p><div class="product-foot"><strong>${fmt(p.price)}</strong><button class="add" data-add="${p.id}" aria-label="Ajouter au panier">+</button></div></div></article>`).join(''):'<p>Aucun produit trouvé.</p>';document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addCart(b.dataset.add))}
function addCart(id){const p=all().find(x=>x.id===id);const x=cart.find(x=>x.id===id);x?x.qty++:cart.push({id:p.id,name:p.name,price:p.price,qty:1});saveCart();toast('Produit ajouté au panier')}
function saveCart(){localStorage.setItem('ailak_cart',JSON.stringify(cart));$('#cartCount').textContent=cart.reduce((s,x)=>s+x.qty,0)}
function renderCart(){$('#cartItems').innerHTML=cart.length?cart.map(x=>`<div class="cart-row"><div><strong>${x.name}</strong><br><small>${x.qty} × ${fmt(x.price)}</small></div><button data-remove="${x.id}">Retirer</button></div>`).join(''):'<p>Votre panier est vide.</p>';$('#cartTotal').textContent=fmt(cart.reduce((s,x)=>s+x.price*x.qty,0));document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{cart=cart.filter(x=>x.id!==b.dataset.remove);saveCart();renderCart()})}
function order(){if(!cart.length)return toast('Ajoutez un produit avant de commander');const name=$('#customerName').value.trim(),phone=$('#customerPhone').value.trim(),area=$('#customerArea').value.trim();if(!name||!phone||!area)return toast('Remplissez votre nom, téléphone et quartier');const lines=cart.map(x=>`• ${x.name} x${x.qty} = ${fmt(x.price*x.qty)}`).join('\n');const total=fmt(cart.reduce((s,x)=>s+x.price*x.qty,0));const message=`Bonjour Ailakshop, je souhaite commander :\n\n${lines}\n\nTotal : ${total}\n\nNom : ${name}\nTéléphone : ${phone}\nLivraison : ${area}\nPaiement : à la livraison`;window.open(`https://wa.me/224622261904?text=${encodeURIComponent(message)}`,'_blank')}
function renderManage(){const el=$('#manageList');el.innerHTML=custom.length?custom.map(p=>`<div class="manage-item"><div><strong>${p.name}</strong><br><small>${fmt(p.price)} · Stock ${p.stock}</small></div><div><button class="secondary" data-edit="${p.id}">Modifier</button><button class="secondary" data-del="${p.id}">Supprimer</button></div></div>`).join(''):'<p>Aucun produit personnel ajouté.</p>';document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editProduct(b.dataset.edit));document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{if(confirm('Supprimer ce produit ?')){custom=custom.filter(p=>p.id!==b.dataset.del);saveProducts()}})}
function editProduct(id){const p=custom.find(x=>x.id===id),f=$('#productForm');['id','name','price','stock','category','description'].forEach(k=>f.elements[k].value=p[k]||'');f.scrollIntoView({behavior:'smooth'})}
function saveProducts(){localStorage.setItem('ailak_products',JSON.stringify(custom));renderCats();renderProducts();renderManage()}
$('#productForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,d=Object.fromEntries(new FormData(f));const old=custom.find(x=>x.id===d.id);let image=old?.image||'';const file=f.elements.image.files[0];if(file)image=await new Promise(r=>{const x=new FileReader;x.onload=()=>r(x.result);x.readAsDataURL(file)});const p={id:d.id||'u'+Date.now(),name:d.name,price:+d.price,stock:+d.stock,category:d.category,description:d.description,image,emoji:'📦'};custom=custom.filter(x=>x.id!==p.id);custom.push(p);saveProducts();f.reset();toast('Produit enregistré')};
$('#sellerForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));const message=`Bonjour Ailakshop, je souhaite devenir vendeur.\n\nNom : ${d.name}\nTéléphone : ${d.phone}\nBoutique : ${d.shop}`;window.open(`https://wa.me/224622261904?text=${encodeURIComponent(message)}`,'_blank');$('#sellerMsg').textContent='Votre demande est prête dans WhatsApp.'};$('#search').oninput=renderProducts;$('#cartBtn').onclick=()=>{renderCart();$('#cartDialog').showModal()};$('#closeCart').onclick=()=>$('#cartDialog').close();$('#orderBtn').onclick=order;$('#toggleManager').onclick=()=>{const p=$('#managerPanel');p.hidden=!p.hidden;$('#toggleManager').textContent=p.hidden?'Afficher la gestion':'Masquer la gestion';if(!p.hidden)renderManage()};$('#menuBtn').onclick=()=>$('#nav').classList.toggle('open');document.querySelectorAll('#nav a').forEach(a=>a.onclick=()=>$('#nav').classList.remove('open'));
renderCats();renderProducts();saveCart();
